spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    non-compact-topic: my-topic-non-compact
    compact-topic: my-topic-compact

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG